### ISSUE TITLE
Issue with fonts in the config file?

### ISSUE THREAD

**Issue by DooDip** [chrissnell/weather-bar#1]
I think the config file has some font errors. I retyped the lines near the bottom and it fixed it. Very cool program!

**Comment by chrissnell** [comment]
Actually, those symbols are present in [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts) but I didn't mention that in the README.  You should install them, the bar will look much better and have nice icons!  :)

I will update the README.  Thanks for pointing that out.
