### ISSUE TITLE
Weather-bar does not display properly

### ISSUE THREAD

**Issue by gvelchuru** [chrissnell/weather-bar#2]
I am now getting the error "json: cannot unmarshal string into Go struct field CurrentObservation.wind_gust_mph of type float64"

**Comment by segmentati0nf4ult** [comment]
Same here

**Comment by chrissnell** [comment]
Yikes.  I will look at this.  Sounds like an upstream struct may have changed.

**Comment by chrissnell** [comment]
WU changed their API without telling anybody.  The v1.1 release has a fix for this.  Would you mind downloading and giving that a shot?

**Comment by gvelchuru** [comment]
Looks fixed!
